server:
  port: 3001

spring:
  application:
    name: FSA Forest Client API
  main:
    lazy-initialization: true
    banner-mode: "off"
    allow-bean-definition-overriding: true
  r2dbc:
    url: r2dbcs:oracle:thin:@tcps://${ca.bc.gov.nrs.oracle.host}/${ca.bc.gov.nrs.oracle.service}
    username: ${ca.bc.gov.nrs.oracle.username}
    password: ${ca.bc.gov.nrs.oracle.password}
    pool:
      enabled: true
      initialSize: 1
      minIdle: 1
      maxSize: 3
      maxLifeTime: 60000
      maxIdleTime: 45000
      maxCreateConnectionTime: 90000
      poolName: ForestClientApiPool

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,metrics

springdoc:
  enable-native-support: true
  swagger-ui:
    path: /
  webjars:
    prefix: /v3
  api-docs:
    groups:
      enabled: true
  show-actuator: false

ca:
  bc:
    gov:
      nrs:
        oracle:
          service: ${ORACLEDB_SERVICENAME:fsa-forest}
          database: ${ORACLEDB_DATABASE:fsa-forest}
          host: ${ORACLEDB_HOST:localhost}:${ORACLEDB_PORT:1521}
          username: ${ORACLEDB_USER:user}
          password: ${ORACLEDB_PASSWORD:passwd}
          schema: THE
