spring:
  datasource:
    url: jdbc:oracle:thin:@${ca.bc.gov.nrs.oracle.host}/${ca.bc.gov.nrs.oracle.service}
  r2dbc:
    url: r2dbc:oracle://${ca.bc.gov.nrs.oracle.host}/${ca.bc.gov.nrs.oracle.database}