name: Merge to Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NAME: ${{ github.event.repository.name }}
  NS: nr-d2723f

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  codeql:
    name: Semantic Code Analysis
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: java

      - name: Set up JDK 17 and Caching maven dependencies
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build for Java
        run: ./mvnw clean package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  sonarcloud:
    name: Static Analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: bcgov-nr/action-test-and-analyse-java@v1.0.0
        with:
          commands: |
            mvn -B verify -P all-tests checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
          dir: .
          java-cache: maven
          java-distribution: temurin
          java-version: "17"
          sonar_args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_forest-client-api
          sonar_token: ${{ secrets.SONAR_TOKEN }}

  trivy-repo:
    name: Repository Report
    needs:
      - codeql
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          scanners: "vuln,secret,config"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"

  deploy-test:
    name: TEST Deployment
    needs:
      - trivy-repo
      - sonarcloud
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
    permissions:
      contents: write
      discussions: write
    environment:
      name: test
    env:
      ZONE: test
      DOMAIN: apps.silver.devops.gov.bc.ca
    steps:
      - uses: actions/checkout@v4

      - name: Deploys
        uses: bcgov-nr/action-deployer-openshift@v2.0.0
        with:
          file: openshift.deploy.yml
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          verification_path: /health
          penetration_test: true
          parameters:
            -p ZONE=${{ env.ZONE }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/api:${{ env.ZONE }}
            -p ORACLEDB_USER=${{ secrets.ORACLEDB_USERNAME }}
            -p ORACLEDB_PASSWORD=${{ secrets.ORACLEDB_PASSWORD }}
            -p ORACLEDB_DATABASE=${{ secrets.ORACLEDB_DATABASE }}
            -p ORACLEDB_HOST=${{ secrets.ORACLEDB_HOST }}
            -p ORACLEDB_SERVICENAME=${{ secrets.ORACLEDB_SERVICENAME }}
            -p ORACLEDB_SECRET=${{ secrets.ORACLEDB_SECRET }}

      - name: Publish API
        uses: bcgov-nr/action-gwa-publish@v0.1.0
        with:
          namespace: ${{ env.NS }}
          client_id: ${{ secrets.GWA_ACCT_ID }}
          client_secret: ${{ secrets.GWA_ACCT_SECRET }}
          file: .github/gwa/service-test.yaml

      - name: Postman Smoke Test on Openshift
        uses: matt-ball/newman-action@master
        with:
          collection: postman/FCA.postman_collection.json
          envVar: '[{"key":"URL_FCA","value":"https://${{ env.NAME }}-test-backend.${{ env.DOMAIN }}"}]'
          reporters: '["cli"]'
          folder: '["general"]'

      - name: Postman Smoke Test on API Gateway
        uses: matt-ball/newman-action@master
        with:
          collection: postman/FCA.postman_collection.json
          envVar: '[{"key":"URL_FCA","value":"https://${{ env.NAME }}-test.api.gov.bc.ca"}]'
          reporters: '["cli"]'
          folder: '["general"]'

      - name: Conventional Changelog Update
        uses: TriPSs/conventional-changelog-action@v4
        id: changelog
        continue-on-error: true
        with:
          github-token: ${{ github.token }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true"
          skip-commit: "true"
          git-push: "true"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: ${{ steps.changelog.outputs.tag != '' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: Log in to the Container registry
        uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  image-promotions:
    name: Image Promotions
    needs:
      - deploy-test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        component: [api, init]
        tag: [prod, "${{ needs.deploy-test.outputs.tag }}"]
    steps:
      - name: Promoting ${{ matrix.component }}
        if: ${{ matrix.tag != '' }}
        uses: shrink/actions-docker-registry-tag@v3
        with:
          registry: ${{ env.REGISTRY }}
          repository: ${{ github.repository }}/${{ matrix.component }}
          target: test
          tags: ${{ matrix.tag }}

      - name: Promoting ${{ matrix.component }}
        if: ${{ matrix.tag == '' }}
        run: echo "Tag is empty, promotion step skipped"

  deploy-prod:
    name: PROD Deployment
    needs:
      - image-promotions
    runs-on: ubuntu-22.04
    environment:
      name: prod
    env:
      ZONE: prod
      PREV: test
      DOMAIN: apps.silver.devops.gov.bc.ca
    steps:
      - uses: actions/checkout@v4

      - name: Deploys
        uses: bcgov-nr/action-deployer-openshift@v2.0.0
        with:
          file: openshift.deploy.yml
          oc_namespace: ${{ secrets.OC_NAMESPACE }}
          oc_server: ${{ secrets.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          overwrite: true
          penetration_test: false
          verification_path: /health
          parameters:
            -p ZONE=${{ env.ZONE }} -p NAME=${{ github.event.repository.name }}
            -p PROMOTE=${{ github.repository }}/api:${{ env.ZONE }}
            -p ORACLEDB_USER=${{ secrets.ORACLEDB_USERNAME }}
            -p ORACLEDB_PASSWORD=${{ secrets.ORACLEDB_PASSWORD }}
            -p ORACLEDB_DATABASE=${{ secrets.ORACLEDB_DATABASE }}
            -p ORACLEDB_HOST=${{ secrets.ORACLEDB_HOST }}
            -p ORACLEDB_SERVICENAME=${{ secrets.ORACLEDB_SERVICENAME }}
            -p ORACLEDB_SECRET=${{ secrets.ORACLEDB_SECRET }}
      - name: Publish API
        uses: bcgov-nr/action-gwa-publish@v0.1.0
        with:
          namespace: ${{ env.NS }}
          client_id: ${{ secrets.GWA_ACCT_ID }}
          client_secret: ${{ secrets.GWA_ACCT_SECRET }}
          file: .github/gwa/service-prod.yaml

      - name: Postman Smoke Test on Openshift
        uses: matt-ball/newman-action@master
        with:
          collection: postman/FCA.postman_collection.json
          envVar: '[{"key":"URL_FCA","value":"https://${{ env.NAME }}-prod-backend.${{ env.DOMAIN }}"}]'
          reporters: '["cli"]'
          folder: '["general"]'

      - name: Postman Smoke Test on API Gateway
        uses: matt-ball/newman-action@master
        with:
          collection: postman/FCA.postman_collection.json
          envVar: '[{"key":"URL_FCA","value":"https://${{ env.NAME }}-prod.api.gov.bc.ca"}]'
          reporters: '["cli"]'
          folder: '["general"]'
