name: Native Build test

on:
  pull_request:

env:
  REGISTRY: ghcr.io
  NAME: nr-forest-client-api
  DOMAIN: apps.silver.devops.gov.bc.ca

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build App
        id: nativebuild
        run: |
          ./mvnw -Pnative clean spring-boot:build-image \
          -Dspring-boot.build-image.imageName="ghcr.io/${{ github.repository }}:${{ github.event.number }}" \
          -Dspring-boot.build-image.publish=true \
          -Ddocker.user="${{ github.actor }}" \
          -Ddocker.user="${{ secrets.GITHUB_TOKEN }}"
