name: Unit Tests and Analysis

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-backend:
    name: Backend Unit Tests
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - uses: bcgov-nr/action-test-and-analyse-java@v1.0.0
        with:
          commands: |
            mvn -B verify -Pall-tests checkstyle:checkstyle -Dcheckstyle.skip=false --file pom.xml
          dir: .
          java-cache: maven
          java-distribution: temurin
          java-version: "17"
          sonar_args: >
            -Dsonar.organization=bcgov-sonarcloud
            -Dsonar.projectKey=bcgov_forest-client-api
          sonar_project_token: ${{ secrets.SONAR_TOKEN }}
      - name: Archive CycloneDX
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: cyclone
          path: target/bom.json
          retention-days: 5

      - name: Use Checkstyle report
        continue-on-error: true
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: "**/checkstyle-result.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        continue-on-error: true
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "target/**/TEST-*.xml"
          commit: ${{ github.event.pull_request.head.sha }}
          summary: Pull Request Tests
          detailed_summary: true
          job_name: Tests

      - name: Add coverage to PR
        id: jacoco
        continue-on-error: true
        uses: madrapps/jacoco-report@v1.6
        with:
          paths: target/coverage-reports/merged-test-report/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 75
          min-coverage-changed-files: 75

  # https://github.com/marketplace/actions/aqua-security-trivy
  trivy:
    name: Repository Report
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.14.0
        with:
          scan-type: "fs"
          format: "sarif"
          output: "trivy-results.sarif"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          scanners: "vuln,secret,config"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
